<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Suffix />
    <VersionYear>2026</VersionYear>
    <VersionMajor>0</VersionMajor>
    <VersionMinor>1</VersionMinor>
    <VersionPatch>0</VersionPatch>
    <Version>$(VersionYear).$(VersionMajor).$(VersionMinor).$(VersionPatch)$(Suffix)</Version>
    <NoWarn>nullable;NU5118;$(NoWarn)</NoWarn>
  </PropertyGroup>
</Project>
