<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Suffix />
    <VersionYear>$([System.DateTime]::UtcNow.Year)</VersionYear>
    <VersionMajor>$([System.DateTime]::UtcNow.Month)</VersionMajor>
    <VersionMinor>$([System.DateTime]::UtcNow.Day)</VersionMinor>
    <VersionPatch>$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::UtcNow.Date)).TotalMinutes.ToString("F0"))</VersionPatch>
    <Stable>$(VersionYear).$(VersionMajor).$(VersionMinor)</Stable>
    <Version>$(Stable).$(VersionPatch)$(Suffix)</Version>
    <NoWarn>nullable;NU5118;$(NoWarn)</NoWarn>
  </PropertyGroup>
</Project>
