namespace NetMediate;

/// <summary>
/// AOT-safe keyed handler registry that maps routing keys to handler factories.
/// Pipeline executors use this registry when a routing key is provided, falling back
/// to the standard Microsoft DI container when the key has no registered factory.
/// </summary>
/// <remarks>
/// The registry is registered as a singleton in the DI container. Its factories are
/// generated by the source generator at compile time — no reflection is needed at
/// run time, making this approach safe for NativeAOT and trimming scenarios.
/// <para>
/// Each factory accepts the active <see cref="IServiceProvider"/> so that scoped and
/// transient dependencies are resolved from the current scope. Singleton handlers
/// capture a <see cref="Lazy{T}"/> in the outer singleton factory, ensuring a single
/// instance regardless of which scope's provider is passed at invocation time.
/// </para>
/// <para>
/// Multiple handlers may be registered under the same key (e.g. two notification
/// handlers that should both fire on the same routing key). Each key maps to an array
/// of factory delegates and the pipeline executor receives all of them.
/// </para>
/// </remarks>
/// <typeparam name="THandler">
/// The handler interface type (e.g. <see cref="ICommandHandler{TMessage}"/>).
/// </typeparam>
public sealed class KeyedHandlerRegistry<THandler>
{
    private readonly IReadOnlyDictionary<object, Func<IServiceProvider, THandler>[]> _factories;

    /// <summary>
    /// Initializes a new registry with the given key-to-factory-array map.
    /// </summary>
    /// <param name="factories">
    /// A dictionary mapping routing keys to arrays of handler factory delegates.
    /// Each delegate receives the active <see cref="IServiceProvider"/> and returns
    /// a handler instance. Singleton factories should ignore the provider and return a
    /// pre-captured <see cref="Lazy{T}.Value"/>; transient and scoped factories should
    /// use the provided <see cref="IServiceProvider"/> to resolve dependencies from the
    /// correct scope.
    /// </param>
    public KeyedHandlerRegistry(IReadOnlyDictionary<object, Func<IServiceProvider, THandler>[]> factories)
        => _factories = factories;

    /// <summary>
    /// Attempts to resolve all handlers registered for <paramref name="key"/>.
    /// </summary>
    /// <param name="key">The routing key to look up.</param>
    /// <param name="serviceProvider">
    /// The active <see cref="IServiceProvider"/> for the current scope. Passed to each
    /// factory delegate so that scoped and transient dependencies are resolved correctly.
    /// </param>
    /// <param name="handlers">
    /// When this method returns <see langword="true"/>, contains one or more resolved
    /// handler instances; otherwise an empty array.
    /// </param>
    /// <returns>
    /// <see langword="true"/> when one or more factories were found for
    /// <paramref name="key"/>; <see langword="false"/> to signal that the caller should
    /// fall back to standard DI resolution.
    /// </returns>
    public bool TryGetAll(object key, IServiceProvider serviceProvider, out THandler[] handlers)
    {
        if (_factories.TryGetValue(key, out var factories))
        {
            handlers = new THandler[factories.Length];
            for (var i = 0; i < factories.Length; i++)
                handlers[i] = factories[i](serviceProvider);
            return true;
        }
        handlers = [];
        return false;
    }
}
