namespace NetMediate;

/// <summary>
/// AOT-safe keyed handler registry that maps routing keys to handler factories.
/// Pipeline executors use this registry when a routing key is provided, falling back
/// to the standard Microsoft DI container when the key has no registered factory.
/// </summary>
/// <remarks>
/// The registry is registered as a singleton in the DI container. Its factories are
/// generated by the source generator at compile time — no reflection is needed at
/// run time, making this approach safe for NativeAOT and trimming scenarios.
/// <para>
/// Transient handlers are represented by a factory delegate that creates a new
/// instance on every call. Singleton handlers use a <see cref="Lazy{T}"/> so that
/// the instance is created once and reused across calls.
/// </para>
/// </remarks>
/// <typeparam name="THandler">
/// The handler interface type (e.g. <see cref="ICommandHandler{TMessage}"/>).
/// </typeparam>
public sealed class KeyedHandlerRegistry<THandler>
{
    private readonly IReadOnlyDictionary<object, Func<THandler>> _factories;

    /// <summary>
    /// Initializes a new registry with the given key-to-factory map.
    /// </summary>
    /// <param name="factories">
    /// A dictionary mapping routing keys to handler factory delegates. The delegate
    /// returns a handler instance; for singletons the delegate should return a cached
    /// instance (e.g. via <see cref="Lazy{T}.Value"/>), whereas for transients it
    /// should create a fresh instance on every invocation.
    /// </param>
    public KeyedHandlerRegistry(IReadOnlyDictionary<object, Func<THandler>> factories)
        => _factories = factories;

    /// <summary>
    /// Attempts to resolve the handler registered for <paramref name="key"/>.
    /// </summary>
    /// <param name="key">The routing key to look up.</param>
    /// <param name="handler">
    /// When this method returns <see langword="true"/>, contains the resolved handler
    /// instance; otherwise <see langword="default"/>.
    /// </param>
    /// <returns>
    /// <see langword="true"/> when a factory was found for <paramref name="key"/>;
    /// <see langword="false"/> to signal that the caller should fall back to standard
    /// DI resolution.
    /// </returns>
    public bool TryGet(object key, out THandler? handler)
    {
        if (_factories.TryGetValue(key, out var factory))
        {
            handler = factory();
            return true;
        }
        handler = default;
        return false;
    }
}
