name: Feature Request
description: Suggest a new feature or enhancement for NetMediate
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.
        
  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: What feature would you like to see in NetMediate?
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Explain why this feature would be useful and what problem it solves.
      placeholder: |
        - What problem does this feature solve?
        - How would this feature improve your development experience?
        - What scenarios would benefit from this feature?
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this feature could be implemented, please share them.
      placeholder: |
        - How do you envision this feature working?
        - What API changes or additions would be needed?
        - Are there any specific design considerations?
    validations:
      required: false
      
  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: If possible, provide an example of how you would use this feature.
      placeholder: |
        ```csharp
        // Example of how the feature might be used
        public class ExampleMessage : IRequest<string>
        {
            public string Data { get; set; }
        }
        
        // New feature usage
        await mediator.SendWithNewFeature(message);
        ```
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - What workarounds are you currently using?
        - Are there alternative approaches to solving this problem?
        - How do other libraries handle similar scenarios?
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your use case?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my current development
    validations:
      required: true
      
  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would you be okay with this feature introducing breaking changes if necessary?
      options:
        - "Yes - Breaking changes are acceptable"
        - "No - Must be backward compatible"
        - "Unsure - Depends on the implementation"
    validations:
      required: true
      
  - type: textarea
    id: related-features
    attributes:
      label: Related Features or Issues
      description: Are there any related features, issues, or discussions?
      placeholder: |
        - Link to related issues: #123
        - Related features in other libraries
        - Community discussions
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: |
        - Documentation references
        - Performance considerations
        - Compatibility requirements
        - Community feedback
    validations:
      required: false