using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;
using static NetMediate.SourceGeneration.Constants;

namespace NetMediate.SourceGeneration;

[Generator]
public sealed class NetMediateRegistrationGenerator : IIncrementalGenerator
{
    private static bool IsGeneratedCodeCoverageEnabled(Compilation compilation)
    {
        var attributeData = compilation.Assembly.GetAttributes()
            .FirstOrDefault(ad => ad.AttributeClass?.ToDisplayString().Replace(GlobalNamespace, "") == "GenDI.GenDICoverationAttribute");

        return attributeData is { ConstructorArguments.Length: 0 }
                || attributeData?.ConstructorArguments[0].Value is not bool includeGeneratedCodeInCoverage
                || includeGeneratedCodeInCoverage;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => Search(node),
                transform: static (ctx, _) => Transform(ctx)
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!)
            .Collect();

        var packageInfo = context.CompilationProvider.Select(
            static (compilation, _) => Selects(compilation)
        );

        var combined = handlerTypes.Combine(packageInfo);

        context.RegisterSourceOutput(
            combined,
            static (sourceProductionContext, input) => Accumulate(sourceProductionContext, input)
        );
    }

    private static void Accumulate(
        SourceProductionContext sourceProductionContext,
        (
            ImmutableArray<INamedTypeSymbol> Left,
            (
                bool hasDiagnostics,
                bool hasResilience,
                bool isNetMediateAssembly,
                string assemblyName,
                bool supportsGlobalUsing,
                string coverage,
                string dependencyChains,
                string duplicateCleanupCall,
                string duplicateCleanupMembers
            ) Right
        ) input
    )
    {
        var (
            types,
            (
                hasDiagnostics,
                hasResilience,
                isNetMediateAssembly,
                assemblyName,
                supportsGlobalUsing,
                coverage,
                dependencyChains,
                duplicateCleanupCall,
                duplicateCleanupMembers
            )
        ) = input;

        if (supportsGlobalUsing)
        {
            sourceProductionContext.AddSource(
                "NetMediateGlobalUsings.g.cs",
                $"// <auto-generated />\n// Auto-import {assemblyName} so AddNetMediate() is discoverable"
                    + $" without a manual 'using {assemblyName};'.\n"
                    + $"global using {assemblyName};\n"
            );
        }

        if (isNetMediateAssembly || types.IsEmpty)
        {
            // This fallback stub does not flow through the template token replacement path,
            // so the coverage attribute must stay fully qualified here.
            sourceProductionContext.AddSource(
                "NetMediateGeneratedDI.g.cs",
                $$"""
                // <auto-generated />
                {{coverage}}public static partial class NetMediateGeneratedDI
                {
                    // No handlers found — no registrations to generate.
                }
                """
            );
            return;
        }

        var behaviorTemplate = LoadBehaviorTemplate().Replace(CoverageToken, coverage);
        var frameworkBehaviors = BuildFrameworkBehaviors(
            types,
            hasDiagnostics,
            hasResilience,
            assemblyName,
            behaviorTemplate
        );

        foreach (var behavior in frameworkBehaviors)
        {
            sourceProductionContext.AddSource($"{behavior.Key}.g.cs", behavior.Value);
        }

        var source = BuildSource(
            assemblyName,
            coverage,
            dependencyChains,
            duplicateCleanupCall,
            duplicateCleanupMembers
        );
        sourceProductionContext.AddSource("NetMediateGeneratedDI.g.cs", source);

        var typedExtensionMethods = BuildTypedExtensionMethods(types);
        var typedExtensionsSource = BuildTypedExtensionsSource(typedExtensionMethods, assemblyName, coverage);
        sourceProductionContext.AddSource("NetMediateTypedExtensions.g.cs", typedExtensionsSource);
    }

    private static (
        bool hasDiagnostics,
        bool hasResilience,
        bool isNetMediateAssembly,
        string assemblyName,
        bool supportsGlobalUsing,
        string coverage,
        string dependencyChains,
        string duplicateCleanupCall,
        string duplicateCleanupMembers
    ) Selects(Compilation compilation)
    {
        var names = compilation.ReferencedAssemblyNames.Select(name => name.Name);
        bool hasDiagnostics = names.Contains("NetMediate.Diagnostics");
        bool hasResilience = names.Contains("NetMediate.Resilience");
        bool isNetMediateAssembly = compilation.AssemblyName?.Replace(GlobalNamespace, "") == PackName;
        bool supportsGlobalUsing =
            compilation is CSharpCompilation { LanguageVersion: >= LanguageVersion.CSharp10 };
        var (dependencyChains, duplicateCleanupCall, duplicateCleanupMembers) =
            BuildDependencyPlan(compilation);

        return (
            hasDiagnostics,
            hasResilience,
            isNetMediateAssembly,
            compilation.AssemblyName,
            supportsGlobalUsing,
            IsGeneratedCodeCoverageEnabled(compilation) ? CoverageTpl : string.Empty,
            dependencyChains,
            duplicateCleanupCall,
            duplicateCleanupMembers
        );
    }

    private static bool Search(SyntaxNode node) =>
        node is TypeDeclarationSyntax declaration && declaration.BaseList is not null;

    private static INamedTypeSymbol? Transform(GeneratorSyntaxContext ctx)
    {
        var declaration = (TypeDeclarationSyntax)ctx.Node;

        if (
            ctx.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol
            || typeSymbol.IsAbstract
            || typeSymbol.IsGenericType
            || !IsAccessible(typeSymbol)
        )
            return null;

        return typeSymbol;
    }

    /// <summary>
    /// Builds the generated framework behavior classes for the discovered handler types.
    /// Uses insertion-ordered dictionaries for deduplication so the same behavior is never
    /// emitted twice even when multiple handlers share the same message type.
    /// </summary>
    private static Dictionary<string, string> BuildFrameworkBehaviors(
        ImmutableArray<INamedTypeSymbol> types,
        bool hasDiagnostics,
        bool hasResilience,
        string assemblyName,
        string template
    )
    {
        List<(string name, string content)> behaviors = [];

        foreach (var handlerType in types)
        {
            behaviors.AddRange(BuildFrameworkBehaviorEntries(
                (
                    template,
                    assemblyName,
                    hasDiagnostics,
                    hasResilience,
                    handlerType
                )
            ));
        }

        return behaviors.GroupBy(behavior => behavior.name)
            .ToDictionary(group => group.Key, group => group.First().content);
    }

    private static IEnumerable<(string, string)> BuildFrameworkBehaviorEntries(
        BuildFrameworkBehaviorArguments arguments
    )
    {
        var(
            behaviorTemplate,
            assemblyName,
            hasDiagnostics,
            hasResilience,
            handlerType
        ) = arguments;

        List<(string, string)> behaviors = [];

        foreach (var @interface in handlerType.AllInterfaces)
        {
            var definition = @interface.OriginalDefinition;
            if (definition.ContainingNamespace.ToDisplayString().Replace(GlobalNamespace, "") != PackName)
                continue;

            var name = definition.Name;
            var arity = definition.Arity;
            var args = @interface.TypeArguments;

            behaviors.AddRange(ProcessHandlerInterface(
                (
                    behaviorTemplate,
                    assemblyName,
                    name,
                    arity,
                    args,
                    hasDiagnostics,
                    hasResilience
                )
            ));
        }

        return behaviors;
    }

    private static IEnumerable<(string, string)> ProcessHandlerInterface(ProcessHandlerInterfaceArguments arguments)
    {
        if (!TryCreateBehaviorRegistration(arguments, out var registration))
            return [];

        return registration.GetBehaviorClasses();
    }

    private static bool TryCreateBehaviorRegistration(
        ProcessHandlerInterfaceArguments arguments,
        out BehaviorRegistration registration
    )
    {
        var (
            template,
            assemblyName,
            interfaceName,
            arity,
            args,
            hasDiagnostics,
            hasResilience
        ) = arguments;

        registration = default;

        if (arity == 1 && args.Length == 1 && IsAccessible(args[0]))
        {
            var msg = args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            registration = interfaceName switch
            {
                CommandHandlerIfce => new BehaviorRegistration(
                    template,
                    assemblyName,
                    CommandHandlerIfce,
                    msg,
                    null,
                    hasDiagnostics,
                    hasResilience
                ),
                NotificationHandlerIfce => new BehaviorRegistration(
                    template,
                    assemblyName,
                    NotificationHandlerIfce,
                    msg,
                    null,
                    hasDiagnostics,
                    hasResilience
                ),
                _ => default
            };

            return registration.MessageFqn is not null;
        }

        if (interfaceName == RequestHandlerIfce && arity == 2 && args.Length == 2 && IsAccessible(args[0]) && IsAccessible(args[1]))
        {
            registration = new BehaviorRegistration(
                template,
                assemblyName,
                RequestHandlerIfce,
                args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                hasDiagnostics,
                hasResilience
            );
            return true;
        }

        if (interfaceName == StreamHandlerIfce && arity == 2 && args.Length == 2 && IsAccessible(args[0]) && IsAccessible(args[1]))
        {
            registration = new BehaviorRegistration(
                template,
                assemblyName,
                StreamHandlerIfce,
                args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                hasDiagnostics,
                hasResilience
            );
            return true;
        }

        return false;
    }

    // -------------------------------------------------------------------------
    // Typed extension method generation
    // -------------------------------------------------------------------------

    private readonly record struct TypedExtEntry(
        string Verb,
        string MessageFqn,
        string MessageName,
        string? ResponseFqn
    );

    /// <summary>
    /// Returns the flattened, PascalCase-style identifier for a fully-qualified type name.
    /// <c>global::MyApp.Commands.PingCommand</c> → <c>MyAppCommandsPingCommand</c>.
    /// </summary>
    private static string FlattenFqn(string fqn)
    {
        var s = fqn.StartsWith(GlobalNamespace, StringComparison.Ordinal)
            ? fqn.Substring(GlobalNamespace.Length)
            : fqn;
        var sb = new StringBuilder(s.Length);
        foreach (var c in s.Where(c => char.IsLetterOrDigit(c) || c == '_'))
        {
            sb.Append(c);
        }

        return sb.Length == 0 ? "Message" : sb.ToString();
    }

    /// <summary>
    /// Collects one unique <see cref="TypedExtEntry"/> per <em>verb + message type</em> across all
    /// discovered handler types. Multiple handlers for the same verb/message pair produce one entry.
    /// </summary>
    private static IReadOnlyList<TypedExtEntry> CollectTypedExtEntries(
        ImmutableArray<INamedTypeSymbol> types
    )
    {
        // Key = "{verb}<unit-separator>{message FQN}" — deduplicates duplicate handlers
        // while keeping distinct dispatch verbs for the same message type.
        var entries = new Dictionary<string, TypedExtEntry>(StringComparer.Ordinal);

        foreach (var handlerType in types)
        {
            foreach (var iface in handlerType.AllInterfaces)
            {
                if (!TryCreateTypedExtEntry(iface, out var entry))
                    continue;

                var key = $"{entry.Verb}{TypedExtKeySeparator}{entry.MessageFqn}";
                if (!entries.ContainsKey(key))
                    entries[key] = entry;
            }
        }

        return [.. entries
            .Values.OrderBy(e => e.Verb, StringComparer.Ordinal)
            .ThenBy(e => e.MessageFqn, StringComparer.Ordinal)
            .ThenBy(e => e.ResponseFqn, StringComparer.Ordinal)];
    }

    private static bool TryCreateTypedExtEntry(INamedTypeSymbol iface, out TypedExtEntry entry)
    {
        var def = iface.OriginalDefinition;
        if (def.ContainingNamespace.ToDisplayString().Replace(GlobalNamespace, "") != PackName)
        {
            entry = default;
            return false;
        }

        var args = iface.TypeArguments;
        if (args.Length == 0 || !IsPubliclyAccessible(args[0]))
        {
            entry = default;
            return false;
        }

        var msgFqn = args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var msgName = args[0].Name;

        switch (def.Name)
        {
            case CommandHandlerIfce when args.Length == 1:
                entry = new TypedExtEntry("Send", msgFqn, msgName, null);
                return true;
            case NotificationHandlerIfce when args.Length == 1:
                entry = new TypedExtEntry("Notify", msgFqn, msgName, null);
                return true;
            case RequestHandlerIfce when args.Length == 2 && IsPubliclyAccessible(args[1]):
                entry = new TypedExtEntry(
                    "Request",
                    msgFqn,
                    msgName,
                    args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                );
                return true;
            case StreamHandlerIfce when args.Length == 2 && IsPubliclyAccessible(args[1]):
                entry = new TypedExtEntry(
                    "Stream",
                    msgFqn,
                    msgName,
                    args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                );
                return true;
            default:
                entry = default;
                return false;
        }
    }

    /// <summary>
    /// Generates the bodies of all typed extension methods for the given entries.
    /// Detects method-name conflicts (same verb + simple message name, different FQN) and
    /// disambiguates using the flattened fully-qualified type name.
    /// </summary>
    private static IEnumerable<string> BuildTypedExtensionMethods(
        ImmutableArray<INamedTypeSymbol> types
    )
    {
        var entries = CollectTypedExtEntries(types);

        if (entries.Count == 0)
            return [];

        // Detect conflicts: same (verb + simpleName), different FQN.
        var nameToFqn = new Dictionary<string, string>(StringComparer.Ordinal);
        var conflicted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var e in entries)
        {
            var baseName = $"{e.Verb}{e.MessageName}Async";
            if (nameToFqn.TryGetValue(baseName, out var existing))
            {
                if (!string.Equals(existing, e.MessageFqn, StringComparison.Ordinal))
                    conflicted.Add(baseName);
            }
            else
            {
                nameToFqn[baseName] = e.MessageFqn;
            }
        }

        var result = new List<string>();
        foreach (var e in entries)
        {
            var baseName = $"{e.Verb}{e.MessageName}Async";
            var methodName = conflicted.Contains(baseName)
                ? $"{e.Verb}{FlattenFqn(e.MessageFqn)}Async"
                : baseName;

            result.Add(GenerateTypedExtensionBlock(e, methodName));
        }

        return result;
    }

    private static string GenerateTypedExtensionBlock(TypedExtEntry e, string methodName)
    {
        const string ind = "    ";
        const string task = $"{GlobalNamespace}System.Threading.Tasks.Task";
        const string ct = $"{GlobalNamespace}System.Threading.CancellationToken";

        var sb = new StringBuilder();
        var batchType =
            $"{GlobalNamespace}System.Collections.Generic.IEnumerable<{e.MessageFqn}>";

        switch (e.Verb)
        {
            case "Send":
            case "Notify":
                var mediatorMethod = e.Verb + $"<{e.MessageFqn}>";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine($"{ind}{ind}=> mediator.{mediatorMethod}(message, cancellationToken);");
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{mediatorMethod}(key, message, cancellationToken);"
                );
                sb.AppendLine();

                // batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {batchType} messages, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{mediatorMethod}(messages, cancellationToken);"
                );
                sb.AppendLine();

                // keyed batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {batchType} messages, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{mediatorMethod}(key, messages, cancellationToken);"
                );
                break;

            case "Request":
                var taskResp = $"{task}<{e.ResponseFqn}>";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Sends a <see cref=\"{e.MessageFqn}\"/> request via the mediator and returns a <see cref=\"{e.ResponseFqn}\"/> response.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {taskResp} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.Request<{e.MessageFqn}, {e.ResponseFqn}>(message, cancellationToken);"
                );
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Sends a <see cref=\"{e.MessageFqn}\"/> request via the mediator with an explicit routing key and returns a <see cref=\"{e.ResponseFqn}\"/> response.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {taskResp} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.Request<{e.MessageFqn}, {e.ResponseFqn}>(key, message, cancellationToken);"
                );
                break;

            case "Stream":
                var asyncEnum =
                    $"{GlobalNamespace}System.Collections.Generic.IAsyncEnumerable<{e.ResponseFqn}>";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Initiates a streaming request for <see cref=\"{e.MessageFqn}\"/> via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {asyncEnum} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.RequestStream<{e.MessageFqn}, {e.ResponseFqn}>(message, cancellationToken);"
                );
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Initiates a streaming request for <see cref=\"{e.MessageFqn}\"/> via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {asyncEnum} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.RequestStream<{e.MessageFqn}, {e.ResponseFqn}>(key, message, cancellationToken);"
                );
                break;
        }

        return sb.ToString();
    }

    private static string BuildTypedExtensionsSource(
        IEnumerable<string> extensionBlocks,
        string assemblyName,
        string coverage
    )
    {
        var body = string.Join("\n", extensionBlocks);

        return LoadTypedExtensionsTemplate()
            .Replace(CoverageToken, coverage)
            .Replace(TypedExtensionsToken, body)
            .Replace(AssemblyNamespaceToken, assemblyName);
    }

    private static string LoadTypedExtensionsTemplate()
    {
        var stream =
            typeof(NetMediateRegistrationGenerator).Assembly.GetManifestResourceStream(
                TypedExtensionsTemplateResourceName
            )
            ?? throw new InvalidOperationException(
                $"Embedded template resource '{TypedExtensionsTemplateResourceName}' was not found. "
                    + "Ensure 'NetMediateTypedExtensions.template' is included as an EmbeddedResource "
                    + "in the NetMediate.SourceGeneration project."
            );
        using (stream)
        using (var reader = new StreamReader(stream))
            return reader.ReadToEnd();
    }

    private static (string dependencyChains, string duplicateCleanupCall, string duplicateCleanupMembers) BuildDependencyPlan(
        Compilation compilation
    )
    {
        var dependencyChains = new List<string>();
        var handlerDescriptorRemovals = new Dictionary<(string serviceType, string serviceKey), int>();
        var threadLocalDescriptorRemovals = new HashSet<(string serviceType, string serviceKey)>();
        var currentAssemblyName = compilation.AssemblyName ?? string.Empty;

        foreach (var assembly in compilation
            .References.Select(reference => compilation.GetAssemblyOrModuleSymbol(reference))
            .OfType<IAssemblySymbol>()
            .GroupBy(assembly => assembly.Name, StringComparer.Ordinal)
            .Select(group => group.First()))
        {
            if (assembly.Name == PackName || assembly.Name == currentAssemblyName)
                continue;

            var addGenDIType = compilation.GetTypeByMetadataName(
                $"{assembly.Name}.DependencyInjection.GenDIServiceCollectionExtensions"
            );
            if (!HasRegistrationMethod(addGenDIType, "AddGenDIServices"))
                continue;

            var addNetMediateType = compilation.GetTypeByMetadataName(
                $"{assembly.Name}.NetMediateGeneratedDI"
            );
            var hasAddNetMediate = HasRegistrationMethod(addNetMediateType, "AddNetMediate");

            if (!hasAddNetMediate)
            {
                dependencyChains.Add(
                    $"        global::{assembly.Name}.DependencyInjection.GenDIServiceCollectionExtensions.AddGenDIServices(services);"
                );
            }

            foreach (var handlerType in EnumerateNamedTypes(assembly.GlobalNamespace))
            {
                if (
                    handlerType.IsAbstract
                    || handlerType.IsGenericType
                    || !IsPubliclyAccessible(handlerType)
                    || !TryGetInjectableAttribute(handlerType, out var injectableAttribute)
                )
                {
                    continue;
                }

                foreach (var @interface in handlerType.AllInterfaces)
                {
                    if (
                        !TryCreateExternalHandlerRegistration(
                            handlerType,
                            @interface,
                            injectableAttribute,
                            out var serviceType,
                            out var serviceKey,
                            out var threadLocalServiceKey
                        )
                    )
                    {
                        continue;
                    }

                    var removalKey = (serviceType, serviceKey ?? "null");
                    handlerDescriptorRemovals.TryGetValue(removalKey, out var currentCount);
                    handlerDescriptorRemovals[removalKey] = currentCount + 1;

                    if (threadLocalServiceKey is not null)
                        threadLocalDescriptorRemovals.Add((serviceType, threadLocalServiceKey));
                }
            }
        }

        var dependencyChainsSource = dependencyChains.Count == 0
            ? string.Empty
            : "        // Referenced dependencies without their own AddNetMediate() entrypoint must be chained first.\n"
                + string.Join("\n", dependencyChains)
                + "\n\n";

        if (handlerDescriptorRemovals.Count == 0 && threadLocalDescriptorRemovals.Count == 0)
            return (dependencyChainsSource, string.Empty, string.Empty);

        var removalLines = threadLocalDescriptorRemovals
            .OrderBy(item => item.serviceType, StringComparer.Ordinal)
            .ThenBy(item => item.serviceKey, StringComparer.Ordinal)
            .Select(item =>
                $"        RemoveAppendedDescriptors(services, startIndex, typeof(global::System.Threading.ThreadLocal<{item.serviceType}>), {item.serviceKey}, 1);"
            )
            .Concat(
                handlerDescriptorRemovals
                    .OrderBy(item => item.Key.serviceType, StringComparer.Ordinal)
                    .ThenBy(item => item.Key.serviceKey, StringComparer.Ordinal)
                    .Select(item =>
                        $"        RemoveAppendedDescriptors(services, startIndex, typeof({item.Key.serviceType}), {item.Key.serviceKey}, {item.Value});"
                    )
            );

        var duplicateCleanupMembers = $$"""

            private static void RemoveExternalHandlerDuplicates(
                global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                int startIndex
            )
            {
        {{string.Join("\n", removalLines)}}
            }

            private static void RemoveAppendedDescriptors(
                global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                int startIndex,
                global::System.Type serviceType,
                object? serviceKey,
                int count
            )
            {
                for (var removed = 0; removed < count; removed++)
                {
                    for (var index = startIndex; index < services.Count; index++)
                    {
                        var descriptor = services[index];
                        if (descriptor.ServiceType != serviceType || !Equals(descriptor.ServiceKey, serviceKey))
                            continue;

                        services.RemoveAt(index);
                        break;
                    }
                }
            }
        """;

        return (
            dependencyChainsSource,
            "\n        RemoveExternalHandlerDuplicates(services, localRegistrationStart);\n",
            duplicateCleanupMembers
        );
    }

    private static bool HasRegistrationMethod(INamedTypeSymbol? typeSymbol, string methodName) =>
        typeSymbol?.GetMembers(methodName)
            .OfType<IMethodSymbol>()
            .Any(method =>
                method.IsStatic
                && method.Parameters.Length > 0
                && method.Parameters[0].Type.ToDisplayString().Replace(GlobalNamespace, "")
                    == "Microsoft.Extensions.DependencyInjection.IServiceCollection"
            ) ?? false;

    private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol childNamespace:
                    foreach (var nestedType in EnumerateNamedTypes(childNamespace))
                        yield return nestedType;
                    break;
                case INamedTypeSymbol namedType:
                    foreach (var nestedType in EnumerateNamedTypes(namedType))
                        yield return nestedType;
                    yield return namedType;
                    break;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamedTypeSymbol typeSymbol)
    {
        foreach (var nestedType in typeSymbol.GetTypeMembers())
        {
            foreach (var child in EnumerateNamedTypes(nestedType))
                yield return child;
            yield return nestedType;
        }
    }

    private static bool TryGetInjectableAttribute(
        INamedTypeSymbol typeSymbol,
        out AttributeData injectableAttribute
    )
    {
        injectableAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(attribute =>
                attribute.AttributeClass?.ContainingNamespace.ToDisplayString() == "GenDI"
                && attribute.AttributeClass.Name == "InjectableAttribute"
            );

        return injectableAttribute is not null;
    }

    private static bool TryCreateExternalHandlerRegistration(
        INamedTypeSymbol handlerType,
        INamedTypeSymbol @interface,
        AttributeData injectableAttribute,
        out string serviceType,
        out string? serviceKey,
        out string? threadLocalServiceKey
    )
    {
        var definition = @interface.OriginalDefinition;
        if (definition.ContainingNamespace.ToDisplayString().Replace(GlobalNamespace, "") != PackName)
        {
            serviceType = string.Empty;
            serviceKey = null;
            threadLocalServiceKey = null;
            return false;
        }

        if (@interface.TypeArguments.Any(argument => !IsPubliclyAccessible(argument)))
        {
            serviceType = string.Empty;
            serviceKey = null;
            threadLocalServiceKey = null;
            return false;
        }

        switch (definition.Name)
        {
            case CommandHandlerIfce when @interface.TypeArguments.Length == 1:
            case NotificationHandlerIfce when @interface.TypeArguments.Length == 1:
            case RequestHandlerIfce when @interface.TypeArguments.Length == 2:
            case StreamHandlerIfce when @interface.TypeArguments.Length == 2:
                break;
            default:
                serviceType = string.Empty;
                serviceKey = null;
                threadLocalServiceKey = null;
                return false;
        }

        serviceType = @interface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        serviceKey = TryGetServiceKeyLiteral(injectableAttribute, out var rawServiceKey)
            ? rawServiceKey
            : "null";
        threadLocalServiceKey = UsesThreadIsolation(injectableAttribute, definition.Name)
            ? QuoteStringLiteral(
                $"gendi:thread:{serviceType}:{handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}:{BuildThreadLocalServiceKeySegment(serviceKey)}"
            )
            : null;
        return true;
    }

    private static bool UsesThreadIsolation(AttributeData injectableAttribute, string handlerInterfaceName)
    {
        var explicitThreadIsolation = injectableAttribute.NamedArguments
            .FirstOrDefault(argument => argument.Key == "ThreadIsolation")
            .Value;

        if (explicitThreadIsolation.Kind != TypedConstantKind.Error && explicitThreadIsolation.Value is int value)
            return value != 0;

        return handlerInterfaceName != NotificationHandlerIfce;
    }

    private static bool TryGetServiceKeyLiteral(AttributeData injectableAttribute, out string literal)
    {
        var keyArgument = injectableAttribute.NamedArguments
            .FirstOrDefault(argument => argument.Key == "Key")
            .Value;

        if (keyArgument.IsNull || keyArgument.Value is null)
        {
            literal = string.Empty;
            return false;
        }

        literal = keyArgument.Value switch
        {
            string value => QuoteStringLiteral(value),
            char value => $"'{(value == '\'' ? "\\'" : value.ToString())}'",
            bool value => value ? "true" : "false",
            sbyte or byte or short or ushort or int or uint or long or ulong or float or double or decimal =>
                Convert.ToString(keyArgument.Value, System.Globalization.CultureInfo.InvariantCulture)
                    ?? QuoteStringLiteral(keyArgument.Value.ToString() ?? string.Empty),
            _ => QuoteStringLiteral(keyArgument.Value.ToString() ?? string.Empty),
        };

        return true;
    }

    private static string BuildThreadLocalServiceKeySegment(string serviceKeyLiteral) =>
        serviceKeyLiteral == "null"
            ? "nokey"
            : serviceKeyLiteral.Trim('"');

    private static string QuoteStringLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string BuildSource(
        string assemblyName,
        string coverage,
        string dependencyChains,
        string duplicateCleanupCall,
        string duplicateCleanupMembers
    )
    {
        return LoadTemplate()
            .Replace(CoverageToken, coverage)
            .Replace(AssemblyNamespaceToken, assemblyName)
            .Replace(DependencyChainsToken, dependencyChains)
            .Replace(DuplicateCleanupCallToken, duplicateCleanupCall)
            .Replace(DuplicateCleanupMembersToken, duplicateCleanupMembers);
    }

    private static string LoadBehaviorTemplate()
    {
        var stream =
            typeof(NetMediateRegistrationGenerator).Assembly.GetManifestResourceStream(
                TemplateBehaviorResourceName
            )
            ?? throw new InvalidOperationException(
                $"Embedded template resource '{TemplateBehaviorResourceName}' was not found. "
                    + "Ensure 'NetMediateFrameworkBehavior.template' is included as an EmbeddedResource "
                    + "in the NetMediate.SourceGeneration project."
            );
        using (stream)
        using (var reader = new StreamReader(stream))
            return reader.ReadToEnd();
    }

    private static string LoadTemplate()
    {
        var stream =
            typeof(NetMediateRegistrationGenerator).Assembly.GetManifestResourceStream(
                TemplateResourceName
            )
            ?? throw new InvalidOperationException(
                $"Embedded template resource '{TemplateResourceName}' was not found. "
                    + "Ensure 'NetMediateGeneratedDI.template' is included as an EmbeddedResource "
                    + "in the NetMediate.SourceGeneration project."
            );
        using (stream)
        using (var reader = new StreamReader(stream))
            return reader.ReadToEnd();
    }

    private static bool IsAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is IArrayTypeSymbol arrayType)
            return IsAccessible(arrayType.ElementType);

        if (typeSymbol is IPointerTypeSymbol pointerType)
            return IsAccessible(pointerType.PointedAtType);

        if (typeSymbol is INamedTypeSymbol namedType)
        {
            if (namedType.TypeArguments.Any(argument => !IsAccessible(argument)))
                return false;

            return IsNamedTypeAccessible(namedType);
        }

        return true;
    }

    private static bool IsNamedTypeAccessible(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
        {
            if (
                current.DeclaredAccessibility
                is not Accessibility.Public
                    and not Accessibility.Internal
            )
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsPubliclyAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is ITypeParameterSymbol or IErrorTypeSymbol)
            return false;

        if (typeSymbol is IArrayTypeSymbol arrayType)
            return IsPubliclyAccessible(arrayType.ElementType);

        if (typeSymbol is IPointerTypeSymbol pointerType)
            return IsPubliclyAccessible(pointerType.PointedAtType);

        if (typeSymbol is INamedTypeSymbol namedType)
        {
            if (namedType.TypeArguments.Any(argument => !IsPubliclyAccessible(argument)))
                return false;

            return IsNamedTypePublic(namedType);
        }

        return true;
    }

    private static bool IsNamedTypePublic(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility is not Accessibility.Public)
                return false;
        }

        return true;
    }
}
