using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NetMediate.SourceGeneration;

[Generator]
public sealed class NetMediateRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.BaseList is not null,
                transform: static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax declaration)
                        return null;

                    if (ctx.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol)
                        return null;

                    if (typeSymbol.IsAbstract || typeSymbol.IsGenericType)
                        return null;

                    return typeSymbol;
                }
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!)
            .Collect();

        context.RegisterSourceOutput(
            handlerTypes,
            static (sourceProductionContext, types) =>
            {
                var registrations = BuildRegistrations(types);
                var source = BuildSource(registrations);
                sourceProductionContext.AddSource(
                    "NetMediateGeneratedDI.g.cs",
                    source
                );
            }
        );
    }

    private static string[] BuildRegistrations(ImmutableArray<INamedTypeSymbol> types)
    {
        var registrations = new HashSet<string>(StringComparer.Ordinal);

        foreach (var handlerType in types)
        {
            var handlerName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            foreach (var @interface in handlerType.AllInterfaces)
            {
                var definition = @interface.OriginalDefinition.ToDisplayString();
                var args = @interface.TypeArguments;

                if (definition == "NetMediate.ICommandHandler<TMessage>" && args.Length == 1)
                {
                    registrations.Add(
                        $"builder.RegisterCommandHandler<{args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {handlerName}>();"
                    );
                    continue;
                }

                if (definition == "NetMediate.INotificationHandler<TMessage>" && args.Length == 1)
                {
                    registrations.Add(
                        $"builder.RegisterNotificationHandler<{args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {handlerName}>();"
                    );
                    continue;
                }

                if (definition == "NetMediate.IRequestHandler<TMessage, TResponse>" && args.Length == 2)
                {
                    registrations.Add(
                        $"builder.RegisterRequestHandler<{args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {handlerName}>();"
                    );
                    continue;
                }

                if (definition == "NetMediate.IStreamHandler<TMessage, TResponse>" && args.Length == 2)
                {
                    registrations.Add(
                        $"builder.RegisterStreamHandler<{args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {handlerName}>();"
                    );
                    continue;
                }

                if (definition == "NetMediate.IValidationHandler<TMessage>" && args.Length == 1)
                {
                    registrations.Add(
                        $"builder.RegisterValidationHandler<{args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {handlerName}>();"
                    );
                }
            }
        }

        return [.. registrations.OrderBy(r => r, StringComparer.Ordinal)];
    }

    private static string BuildSource(string[] registrations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace NetMediate;");
        sb.AppendLine();
        sb.AppendLine("public static class NetMediateGeneratedDI");
        sb.AppendLine("{");
        sb.AppendLine("    public static IMediatorServiceBuilder AddNetMediateGenerated(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = services.AddNetMediate(static _ => { });");

        foreach (var registration in registrations)
            sb.AppendLine($"        {registration}");

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
