using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using static NetMediate.SourceGeneration.Constants;

namespace NetMediate.SourceGeneration;

[Generator]
[ExcludeFromCodeCoverage]
public sealed class NetMediateRegistrationGenerator : IIncrementalGenerator
{
    private static bool IsGeneratedCodeCoverageEnabled(Compilation compilation)
    {
        var attributeData = compilation.Assembly.GetAttributes()
            .FirstOrDefault(ad => ad.AttributeClass?.ToDisplayString().Replace(GlobalNamespace, "") == "GenDI.GenDICoverationAttribute");

        return attributeData is { ConstructorArguments.Length: 0 }
                || attributeData?.ConstructorArguments[0].Value is not bool includeGeneratedCodeInCoverage
                || includeGeneratedCodeInCoverage;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => Search(node),
                transform: static (ctx, _) => Transform(ctx)
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!)
            .Collect();

        var packageInfo = context.CompilationProvider.Select(
            static (compilation, _) => Selects(compilation)
        );

        var combined = handlerTypes.Combine(packageInfo);

        context.RegisterSourceOutput(
            combined,
            static (sourceProductionContext, input) => Accumulate(sourceProductionContext, input)
        );
    }

    private static void Accumulate(
        SourceProductionContext sourceProductionContext,
        (
            ImmutableArray<INamedTypeSymbol> Left,
            (
                bool hasResilience,
                bool isNetMediateAssembly,
                string assemblyName,
                bool supportsGlobalUsing,
                string coverage
            ) Right
        ) input
    )
    {
        var (
            types,
            (
                hasResilience,
                isNetMediateAssembly,
                assemblyName,
                supportsGlobalUsing,
                coverage
            )
        ) = input;

        if (supportsGlobalUsing)
        {
            sourceProductionContext.AddSource(
                "NetMediateGlobalUsings.g.cs",
                $"// <auto-generated />\n// Auto-import {assemblyName} so AddNetMediate() is discoverable"
                    + $" without a manual 'using {assemblyName};'.\n"
                    + $"global using {assemblyName};\n"
            );
        }

        if ((isNetMediateAssembly && !hasResilience) || types.IsEmpty)
        {
            // This fallback stub does not flow through the template token replacement path,
            // so the coverage attribute must stay fully qualified here.
            sourceProductionContext.AddSource(
                "NetMediateGeneratedDI.g.cs",
                $$"""
                // <auto-generated />
                using global::NetMediate;
                using Microsoft.Extensions.DependencyInjection.Extensions;

                namespace {{assemblyName}};

                /// <summary>Generated mediator handler registration extension methods.</summary>
                {{coverage}}public static partial class NetMediateGeneratedDI
                {
                    /// <summary>Registers all discovered handlers with the mediator using AOT-safe closed-type registration.</summary>
                    /// <remarks>Returns the same <see cref="global::Microsoft.Extensions.DependencyInjection.IServiceCollection"/> instance for chaining.
                    /// Callers that previously expected a dedicated mediator builder should continue configuring DI from the returned service collection.</remarks>
                    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddNetMediate(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    {
                        services.RegisterNetMediate();

                        // No handlers found — no registrations to generate.

                        return services;
                    }
                }
                """
            );
            return;
        }

        var source = BuildSource(
            assemblyName,
            coverage
        ).Replace(AddNetMediateResilienceDIToken, hasResilience ? "services.AddResilience();" : string.Empty);

        sourceProductionContext.AddSource("NetMediateGeneratedDI.g.cs", source);

        var typedExtensionMethods = BuildTypedExtensionMethods(types);
        var typedExtensionsSource = BuildTypedExtensionsSource(typedExtensionMethods, assemblyName, coverage);
        sourceProductionContext.AddSource("NetMediateTypedExtensions.g.cs", typedExtensionsSource);
    }

    private static (
        bool hasResilience,
        bool isNetMediateAssembly,
        string assemblyName,
        bool supportsGlobalUsing,
        string coverage
    ) Selects(Compilation compilation)
    {
        var names = compilation.ReferencedAssemblyNames.Select(name => name.Name);
        bool hasResilience = names.Contains("NetMediate.Resilience");
        bool isNetMediateAssembly = compilation.AssemblyName?.Replace(GlobalNamespace, "") == PackName;
        bool supportsGlobalUsing =
            compilation is CSharpCompilation { LanguageVersion: >= LanguageVersion.CSharp10 };

        return (
            hasResilience,
            isNetMediateAssembly,
            compilation.AssemblyName,
            supportsGlobalUsing,
            IsGeneratedCodeCoverageEnabled(compilation) ? CoverageTpl : string.Empty
        );
    }

    private static bool Search(SyntaxNode node) =>
        node is TypeDeclarationSyntax declaration && declaration.BaseList is not null;

    private static INamedTypeSymbol? Transform(GeneratorSyntaxContext ctx)
    {
        var declaration = (TypeDeclarationSyntax)ctx.Node;

        if (
            ctx.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol
            || typeSymbol.IsAbstract
            || typeSymbol.IsGenericType
            || !IsAccessible(typeSymbol)
        )
            return null;

        return typeSymbol;
    }

    // -------------------------------------------------------------------------
    // Typed extension method generation
    // -------------------------------------------------------------------------

    private readonly record struct TypedExtEntry(
        string Verb,
        string MessageFqn,
        string MessageName,
        string? ResponseFqn
    );

    /// <summary>
    /// Returns the flattened, PascalCase-style identifier for a fully-qualified type name.
    /// <c>global::MyApp.Commands.PingCommand</c> → <c>MyAppCommandsPingCommand</c>.
    /// </summary>
    private static string FlattenFqn(string fqn)
    {
        var s = fqn.StartsWith(GlobalNamespace, StringComparison.Ordinal)
            ? fqn.Substring(GlobalNamespace.Length)
            : fqn;
        var sb = new StringBuilder(s.Length);
        foreach (var c in s.Where(c => char.IsLetterOrDigit(c) || c == '_'))
        {
            sb.Append(c);
        }

        return sb.Length == 0 ? "Message" : sb.ToString();
    }

    /// <summary>
    /// Collects one unique <see cref="TypedExtEntry"/> per <em>verb + message type</em> across all
    /// discovered handler types. Multiple handlers for the same verb/message pair produce one entry.
    /// </summary>
    private static IReadOnlyList<TypedExtEntry> CollectTypedExtEntries(
        ImmutableArray<INamedTypeSymbol> types
    )
    {
        // Key = "{verb}<unit-separator>{message FQN}" — deduplicates duplicate handlers
        // while keeping distinct dispatch verbs for the same message type.
        var entries = new Dictionary<string, TypedExtEntry>(StringComparer.Ordinal);

        foreach (var handlerType in types)
        {
            foreach (var iface in handlerType.AllInterfaces)
            {
                if (!TryCreateTypedExtEntry(iface, out var entry))
                    continue;

                var key = $"{entry.Verb}{TypedExtKeySeparator}{entry.MessageFqn}";
                if (!entries.ContainsKey(key))
                    entries[key] = entry;
            }
        }

        return [.. entries
            .Values.OrderBy(e => e.Verb, StringComparer.Ordinal)
            .ThenBy(e => e.MessageFqn, StringComparer.Ordinal)
            .ThenBy(e => e.ResponseFqn, StringComparer.Ordinal)];
    }

    private static bool TryCreateTypedExtEntry(INamedTypeSymbol iface, out TypedExtEntry entry)
    {
        var def = iface.OriginalDefinition;
        if (def.ContainingNamespace.ToDisplayString().Replace(GlobalNamespace, "") != PackName)
        {
            entry = default;
            return false;
        }

        var args = iface.TypeArguments;
        if (args.Length == 0 || !IsPubliclyAccessible(args[0]))
        {
            entry = default;
            return false;
        }

        var msgFqn = args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var msgName = args[0].Name;

        switch (def.Name)
        {
            case CommandHandlerIfce when args.Length == 1:
                entry = new TypedExtEntry("Send", msgFqn, msgName, null);
                return true;
            case NotificationHandlerIfce when args.Length == 1:
                entry = new TypedExtEntry("Notify", msgFqn, msgName, null);
                return true;
            case RequestHandlerIfce when args.Length == 2 && IsPubliclyAccessible(args[1]):
                entry = new TypedExtEntry(
                    "Request",
                    msgFqn,
                    msgName,
                    args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                );
                return true;
            case StreamHandlerIfce when args.Length == 2 && IsPubliclyAccessible(args[1]):
                entry = new TypedExtEntry(
                    "Stream",
                    msgFqn,
                    msgName,
                    args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                );
                return true;
            default:
                entry = default;
                return false;
        }
    }

    /// <summary>
    /// Generates the bodies of all typed extension methods for the given entries.
    /// Detects method-name conflicts (same verb + simple message name, different FQN) and
    /// disambiguates using the flattened fully-qualified type name.
    /// </summary>
    private static IEnumerable<string> BuildTypedExtensionMethods(
        ImmutableArray<INamedTypeSymbol> types
    )
    {
        var entries = CollectTypedExtEntries(types);

        if (entries.Count == 0)
            return [];

        var nameToFqn = new Dictionary<string, string>(StringComparer.Ordinal);
        var conflicted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var e in entries)
        {
            var baseName = $"{e.Verb}{e.MessageName}Async";
            if (nameToFqn.TryGetValue(baseName, out var existing))
            {
                if (!string.Equals(existing, e.MessageFqn, StringComparison.Ordinal))
                    conflicted.Add(baseName);
            }
            else
            {
                nameToFqn[baseName] = e.MessageFqn;
            }
        }

        var result = new List<string>();
        foreach (var e in entries)
        {
            var baseName = $"{e.Verb}{e.MessageName}Async";
            var methodName = conflicted.Contains(baseName)
                ? $"{e.Verb}{FlattenFqn(e.MessageFqn)}Async"
                : baseName;

            result.Add(GenerateTypedExtensionBlock(e, methodName));
        }

        return result;
    }

    private static string GenerateTypedExtensionBlock(TypedExtEntry e, string methodName)
    {
        const string ind = "    ";
        const string task = $"{GlobalNamespace}System.Threading.Tasks.ValueTask";
        const string ct = $"{GlobalNamespace}System.Threading.CancellationToken";

        var sb = new StringBuilder();
        var batchType =
            $"{GlobalNamespace}System.Collections.Generic.IEnumerable<{e.MessageFqn}>";

        switch (e.Verb)
        {
            case "Notify":
                methodName = methodName.Replace("Async", string.Empty);
                var notifyMediatorMethod = $"Notify<{e.MessageFqn}>";
                var notifyMediatorMethodBatch = $"Notifies<{e.MessageFqn}>";
                var notifyBatchMethod = methodName + "Batch";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static void {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message)"
                );
                sb.AppendLine($"{ind}{ind}=> mediator.{notifyMediatorMethod}(message);");
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static void {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{notifyMediatorMethod}(key, message);"
                );
                sb.AppendLine();

                // batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static void {notifyBatchMethod}(this {GlobalNamespace}NetMediate.IMediator mediator, {batchType} messages)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{notifyMediatorMethodBatch}(messages);"
                );
                sb.AppendLine();

                // keyed batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static void {notifyBatchMethod}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {batchType} messages)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{notifyMediatorMethodBatch}(key, messages);"
                );
                break;

            case "Send":
                var commandMediatorMethod = $"Send<{e.MessageFqn}>";
                var commandMediatorMethodBatch = $"Sends<{e.MessageFqn}>";
                var commandBatchMethod = methodName.Replace("Async", "BatchAsync");

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine($"{ind}{ind}=> mediator.{commandMediatorMethod}(message, cancellationToken);");
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a <see cref=\"{e.MessageFqn}\"/> message via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{commandMediatorMethod}(key, message, cancellationToken);"
                );
                sb.AppendLine();

                // batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {commandBatchMethod}(this {GlobalNamespace}NetMediate.IMediator mediator, {batchType} messages, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{commandMediatorMethodBatch}(messages, cancellationToken);"
                );
                sb.AppendLine();

                // keyed batch overload
                sb.AppendLine(
                    $"{ind}/// <summary>Dispatches a batch of <see cref=\"{e.MessageFqn}\"/> messages via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {task} {commandBatchMethod}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {batchType} messages, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.{commandMediatorMethodBatch}(key, messages, cancellationToken);"
                );
                break;

            case "Request":
                var taskResp = $"{task}<{e.ResponseFqn}>";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Sends a <see cref=\"{e.MessageFqn}\"/> request via the mediator and returns a <see cref=\"{e.ResponseFqn}\"/> response.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {taskResp} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.Request<{e.MessageFqn}, {e.ResponseFqn}>(message, cancellationToken);"
                );
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Sends a <see cref=\"{e.MessageFqn}\"/> request via the mediator with an explicit routing key and returns a <see cref=\"{e.ResponseFqn}\"/> response.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {taskResp} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.Request<{e.MessageFqn}, {e.ResponseFqn}>(key, message, cancellationToken);"
                );
                break;

            case "Stream":
                var asyncEnum =
                    $"{GlobalNamespace}System.Collections.Generic.IAsyncEnumerable<{e.ResponseFqn}>";

                // key-less overload
                sb.AppendLine(
                    $"{ind}/// <summary>Initiates a streaming request for <see cref=\"{e.MessageFqn}\"/> via the mediator.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {asyncEnum} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.RequestStream<{e.MessageFqn}, {e.ResponseFqn}>(message, cancellationToken);"
                );
                sb.AppendLine();

                // keyed overload
                sb.AppendLine(
                    $"{ind}/// <summary>Initiates a streaming request for <see cref=\"{e.MessageFqn}\"/> via the mediator with an explicit routing key.</summary>"
                );
                sb.AppendLine(
                    $"{ind}public static {asyncEnum} {methodName}(this {GlobalNamespace}NetMediate.IMediator mediator, object? key, {e.MessageFqn} message, {ct} cancellationToken = default)"
                );
                sb.AppendLine(
                    $"{ind}{ind}=> mediator.RequestStream<{e.MessageFqn}, {e.ResponseFqn}>(key, message, cancellationToken);"
                );
                break;
        }

        return sb.ToString();
    }

    private static string BuildTypedExtensionsSource(
        IEnumerable<string> extensionBlocks,
        string assemblyName,
        string coverage
    )
    {
        var body = string.Join("\n", extensionBlocks);

        return LoadTypedExtensionsTemplate()
            .Replace(CoverageToken, coverage)
            .Replace(TypedExtensionsToken, body)
            .Replace(AssemblyNamespaceToken, assemblyName);
    }

    private static string LoadTypedExtensionsTemplate()
    {
        var stream =
            typeof(NetMediateRegistrationGenerator).Assembly.GetManifestResourceStream(
                TypedExtensionsTemplateResourceName
            )
            ?? throw new InvalidOperationException(
                $"Embedded template resource '{TypedExtensionsTemplateResourceName}' was not found. "
                    + "Ensure 'NetMediateTypedExtensions.template' is included as an EmbeddedResource "
                    + "in the NetMediate.SourceGeneration project."
            );
        using (stream)
        using (var reader = new StreamReader(stream))
            return reader.ReadToEnd();
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol childNamespace:
                    foreach (var nestedType in EnumerateNamedTypes(childNamespace))
                        yield return nestedType;
                    break;
                case INamedTypeSymbol namedType:
                    foreach (var nestedType in EnumerateNamedTypes(namedType))
                        yield return nestedType;
                    yield return namedType;
                    break;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamedTypeSymbol typeSymbol)
    {
        foreach (var nestedType in typeSymbol.GetTypeMembers())
        {
            foreach (var child in EnumerateNamedTypes(nestedType))
                yield return child;
            yield return nestedType;
        }
    }

    private static string BuildSource(
        string assemblyName,
        string coverage
    )
    {
        return LoadTemplate()
            .Replace(CoverageToken, coverage)
            .Replace(AssemblyNamespaceToken, assemblyName);
    }

    private static string LoadTemplate()
    {
        var stream =
            typeof(NetMediateRegistrationGenerator).Assembly.GetManifestResourceStream(
                TemplateResourceName
            )
            ?? throw new InvalidOperationException(
                $"Embedded template resource '{TemplateResourceName}' was not found. "
                    + "Ensure 'NetMediateGeneratedDI.template' is included as an EmbeddedResource "
                    + "in the NetMediate.SourceGeneration project."
            );
        using (stream)
        using (var reader = new StreamReader(stream))
            return reader.ReadToEnd();
    }

    private static bool IsAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is IArrayTypeSymbol arrayType)
            return IsAccessible(arrayType.ElementType);

        if (typeSymbol is IPointerTypeSymbol pointerType)
            return IsAccessible(pointerType.PointedAtType);

        if (typeSymbol is INamedTypeSymbol namedType)
        {
            if (namedType.TypeArguments.Any(argument => !IsAccessible(argument)))
                return false;

            return IsNamedTypeAccessible(namedType);
        }

        return true;
    }

    private static bool IsNamedTypeAccessible(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
        {
            if (
                current.DeclaredAccessibility
                is not Accessibility.Public
                    and not Accessibility.Internal
            )
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsPubliclyAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is ITypeParameterSymbol or IErrorTypeSymbol)
            return false;

        if (typeSymbol is IArrayTypeSymbol arrayType)
            return IsPubliclyAccessible(arrayType.ElementType);

        if (typeSymbol is IPointerTypeSymbol pointerType)
            return IsPubliclyAccessible(pointerType.PointedAtType);

        if (typeSymbol is INamedTypeSymbol namedType)
        {
            if (namedType.TypeArguments.Any(argument => !IsPubliclyAccessible(argument)))
                return false;

            return IsNamedTypePublic(namedType);
        }

        return true;
    }

    private static bool IsNamedTypePublic(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility is not Accessibility.Public)
                return false;
        }

        return true;
    }
}
