<Project>
	<ItemGroup>
		<PackageReference Include="NetMediate" Version="2026.*" />
		<PackageReference Include="GenDI.SourceGenerator" Version="26.5.12.1224" PrivateAssets="all">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
