<Project>
	<Target Name="UnlockTransitiveAnalyser" BeforeTargets="_GenerateProjectLintProperties;GetCopyOutputDirectoryItems">
		<ItemGroup>
			<PackageReference Update="NetMediate.SourceGeneration">
				<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
				<PrivateAssets>all</PrivateAssets>
			</PackageReference>

			<PackageReference Update="GenDI.SourceGenerator">
				<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
				<PrivateAssets>contentfiles; compile; runtime</PrivateAssets>
			</PackageReference>
		</ItemGroup>
	</Target>
</Project>
